name: NGINX image builder

on:
  push:
    branches:
    - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Auth on docker hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and push nginx image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./
          file: ./nginx-stable-alpine.Dockerfile
          push: true
          tags: |
            roneikunkel/nginx-stable-alpine:latest
