name: PHP image builder

on:
  push:
    branches:
    - main

jobs:
  CI-PROD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Auth on docker hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and push prod php docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./
          file: ./php82-fpm-alpine.Dockerfile
          push: true
          tags: |
            roneikunkel/php82-fpm-alpine:latest

  CI-TESTING:
    runs-on: ubuntu-latest
    needs: [CI-PROD]
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Auth on docker hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and push testing php docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./
          file: ./php82-fpm-alpine.testing.Dockerfile
          push: true
          tags: |
            roneikunkel/php82-fpm-alpine-testing:latest
